Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[25c6ab2] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[f795b18] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[9ff1df2] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[8ba6375] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[457c77c] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[2e1aefa] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[9fac670] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[d935f94] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[80fd3c5] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[8d12f92] 2021-01-04: nuevo
Error in push(repo) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[8028628] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[4fbdbf6] 2021-01-04: nuevo
[d494cdf] 2021-01-04: nuevo
[ff26e0b] 2021-01-04: nuevo
[a979dab] 2021-01-04: nuevo
[6ad46c7] 2021-01-04: nuevo
[e277935] 2021-01-04: nuevo
[fb67151] 2021-01-04: nuevo
[385098e] 2021-01-04: nuevo
[7d2b3dd] 2021-01-04: nuevo
[b0429b9] 2021-01-04: nuevo
[338bdbf] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': failed to resolve address for github.com: nodename nor servname provided, or not known
Ejecuci'on interrumpida
[d8eefa3] 2021-01-05: nuevo
[bd4e460] 2021-01-05: nuevo
[942b1a6] 2021-01-05: nuevo
[f29bfa7] 2021-01-05: nuevo
[f4f3162] 2021-01-05: nuevo
[6e8cc31] 2021-01-05: nuevo
[9debc7d] 2021-01-05: nuevo
[49a2c76] 2021-01-05: nuevo
[ee8c8ac] 2021-01-05: nuevo
[094dfdb] 2021-01-05: nuevo
