Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[25c6ab2] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[f795b18] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[9ff1df2] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[8ba6375] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[457c77c] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[2e1aefa] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[9fac670] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[d935f94] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
